### PR TITLE
#81: Replacing tidy with local plugin

### LINKED ISSUE #81: jekyll-tidy likely broke search.json
Search does not work on the web. The json (/search.json) does not parse in JS. It seems to be caused by newlines in the html snippets within the json.

Can you please disable the tool on the json?

### PR DESCRIPTION
**Pull request by ufonzak**
Closes #81 

I don't like that jekyll-tidy allows only to exclude files instead of including specific ones. So I got inspired by it and wrote a small plugin of our own.

I've compared all the generated files before and after (including the tree itself). Only HTML files are affected. I also checked the content of the files. It all seems fine. The beautifier will break inline JS if we ever want to do that but that would be discovered during dev.

### CODE REVIEW

**Comment by jankrcal** [comment]
Code-wise, looks good to me, thanks! As I am neither very familiar with Ruby nor with Jekyll, looping in @mukrop.

**Review by jankrcal — APPROVED** [review]

**Review by mukrop — CHANGES_REQUESTED** [review]
Nice. `jekyll-tidy` was just a wrapper over `htmlbeautifier`, so the behavior should be the same (this way, we may be even better able to configure `htmlbeautifier`).

However, I have one thing to discuss: used hooks in this and other plugins.
* Here, you use `:post_render` on `:pages` and `:documents` and still `:after_reset` on the whole `:site`. Is that not duplicating? (The regenerated documents would call `:post_render` anyway, would they not?)
* This plugin now processes pages one by one (and the whole site at reset? see above). Other plugins we have (`space-replacement` and its localized versions) are called just `:post_render` on the whole `:site`. Do we want to unify this?
* Sidenote: If there are multiple hooked plugins post-render, what order are they called in?
* The other custom plugins we now have have a logger entry. If we decide to do the beautification just on the whole `:site`, maybe adding a log line would be nice.

Any comments from @mgrabovsky? (I think it was mostly you doing the other plugins.)

File: _plugins/html-beautify.rb [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+      return @include_paths.any? { |pattern| File.fnmatch(pattern, path) }
+    end
+
+    def self.process(output)
+      return HtmlBeautifier.beautify output
+    end
+  end
+end
+
+Jekyll::Hooks.register :site, :after_reset do |jekyll|
```
Comment (mgrabovsky) [inline _plugins/html-beautify.rb:21]: You could pop these blocks inside the `Jekyll` module as well and lose the `Jekyl::` qualifiers. It'd make the code a wee bit cleaner in my opinion.

**Comment by ufonzak** [comment]
> Nice. `jekyll-tidy` was just a wrapper over `htmlbeautifier`, so the behavior should be the same (this way, we may be even better able to configure `htmlbeautifier`).
> 
> However, I have one thing to discuss: used hooks in this and other plugins.
> 
> * Here, you use `:post_render` on `:pages` and `:documents` and still `:after_reset` on the whole `:site`. Is that not duplicating? (The regenerated documents would call `:post_render` anyway, would they not?)

The after_reset merely initializes config. I don't see any duplication or don't understand the comment.

> * This plugin now processes pages one by one (and the whole site at reset? see above). Other plugins we have (`space-replacement` and its localized versions) are called just `:post_render` on the whole `:site`. Do we want to unify this?

I merely copied the original code and make few changes. I can do it, but maybe there is a reason why the original authors did it this way. Perhaps a better solution for incremental rebuilds if we ever decide to allow them?

> * Sidenote: If there are multiple hooked plugins post-render, what order are they called in?

No idea. We probably want to call this later rather than sooner. In any case, the order does not really matter for this.

> * The other custom plugins we now have have a logger entry. If we decide to do the beautification just on the whole `:site`, maybe adding a log line would be nice.

Can do.

> 
> Any comments from @mgrabovsky? (I think it was mostly you doing the other plugins.)

I put everything into a single hook as the other plugins do. If you like it we can keep it or strip the commit. I am happy either way.

Please do keep in mind that I have no experience with ruby or its technology stack.

File: _plugins/html-beautify.rb (hunk 1 above)
Comment (ufonzak) [reply _plugins/html-beautify.rb]: Done.

**Comment by ufonzak** [comment]
@mukrop Have your issues been resolved?

**Review by mgrabovsky — APPROVED** [review]
Looks good to me personally.

**Review by mukrop — APPROVED** [review]
Seems good (and search stiull works :-)).
